# unit: ms; Byte
seed: 0
num_disks: 4
max_disks: 10
block_size: 4096
chunk_size: 4096
req_size: 4096
raid_level: 5
# 'LS' or 'LA'
raid5_type: 'LS'
solve: True
# 打印 read/write requests
print_physical: True

# Disk
num_tracks: 100
blocks_per_track: 100
seek_time: 10
xfer_time: 0.1
queue_len: 8
# 磁盘休眠超时
# 与 time_interval 保持相同
# sleep_timeout: 100

# trace file path
raw_file: "./trace/hm_1_min.csv"
process_file: "./trace/hm_1_processed.csv"
# process_file: "./trace/generated.csv"

# time interval for IO statistics and for disk sleep timeout
time_interval: 5000000

# predictor
t_up: 2
t_down: 1.5
n_step: 2
miu: 0.5

# RAID mode
# conventional, thinraid, no migration algorithm, no power control policy
mode: 'no migration algorithm'

### DEFAULT CONFIGS ###